name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite rodar manualmente a qualquer momento

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics - Visão Geral
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.classic.svg
          base: header, activity, community, repositories
          config_theme: dark
          plugin_lines: yes

      - name: Metrics - Linguagens
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 8
          config_theme: dark
